rounds = {}

function rounds.next()
  local currentRound = rounds.getCurrent()
  if currentRound >= 4 then
    return
  end

  station.nextRound()
  centerTiles.nextRound()
  headquarters.nextRound(currentRound + 1)
  players.nextRound()

  if currentRound >= 3 then
    hideButtons()
  end
end

function rounds.getCurrent()
  local centerTiles = centerTiles.getPlaced()
  if #centerTiles == 0 then
    return 0
  else
    return 5 - #centerTiles
  end
end
